services:
  db:
    image: postgres:15.8-alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    depends_on:
      - db
    
      