# Generated by Django 5.1.2 on 2024-10-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='xpto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
